### ISSUE TITLE
finding an apartment

### ISSUE THREAD

**Issue by syves** [syves/jettSettersGO#24]

**Comment by syves** [comment]
air bnb for oct 5th- nov 5th 

berlin 1000-1500https://www.airbnb.com/s/berlin?checkin=10%2F05%2F2016&checkout=11%2F06%2F2016&room_types%5B%5D=Entire+home%2Fapt&ss_id=75nx5fug&s_tag=dRw8i0pT

stcokholm 1200-2000
https://www.airbnb.com/s/stockholm?checkin=10%2F05%2F2016&checkout=11%2F06%2F2016&room_types%5B%5D=Entire+home%2Fapt&price_max=2029&ss_id=spv73h02&s_tag=seFLkH7j

amsterdam 1500-2000 and up to 2400 in nov-dec
https://www.airbnb.com/s/amsterdam?checkin=11%2F05%2F2016&checkout=11%2F06%2F2016&room_types%5B%5D=Entire+home%2Fapt&ss_id=p2r9o9xy&s_tag=1Ghz_XAK

stay in air bnb for 3 months while residency apps in progress

contact leasers to findout timeline Jan 1st or feb 1st move in date?

https://jonworth.eu/how-to-find-a-flat-in-berlin/

**Comment by syves** [comment]
berlin 3 months rental deposit 
2.38 x rent for placement ~ $4800 if rent is $800 eu

**Comment by syves** [comment]
http://moving2stockholm.blogspot.com/2015/01/rent-apartment-in-stockholm.html up to $1600n usd

http://www.amsterdamtips.com/tips/finding-flat-for-rent-amsterdam.php $2500usd  rent!!

**Comment by syves** [comment]
https://www.nestpick.com/all/?sort=&q=&location_lat=&location_lng=&min_lat=&min_lng=&max_lat=&max_lng=&distance=10&location_city=17&start-date=2016-10-12&end-date=2017-10-13&category%5B2%5D=2&price=300-1206&females=1&males=1&sort=popularity&room_size=&bed_type%5B0%5D=Double&closet_in_room%5B0%5D=yes&housemates=0&q=

**Comment by syves** [comment]
http://www.immonet.de/angebot/17396065?drop=sel

**Comment by davidchambers** [comment]
Closing in favour of #43, #44, and #45.
